### ISSUE TITLE
crosswalk user agent unknown

### ISSUE THREAD

**Issue by christophehurpeau** [Financial-Times/polyfill-useragent-normaliser#1]
Hello,

This user agent:

[`Mozilla/5.0 (Linux; Android 6.0; PLK-L01 Build/HONORPLK-L01) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Crosswalk/23.53.589.2 Mobile Safari/537.36 LibertyBrowser/1.5.3`](https://cdn.polyfill.io/v2/polyfill.js?features=default,es6,es7,es2017&unknown=polyfill&ua=Mozilla/5.0%20(Linux;%20Android%206.0;%20PLK-L01%20Build/HONORPLK-L01)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/53.0.2785.143%20Crosswalk/23.53.589.2%20Mobile%20Safari/537.36%20LibertyBrowser/1.5.3)

is recognized as `crosswalk/23.53.0`

```
* UA detected: crosswalk/23.53.0 (unknown/unsupported; using policy `unknown=polyfill`)
```

It is a chrome webview, so it should be probably recognized as `chrome/53`

**Comment by JakeChampion** [comment]
Should be similar solution as #9
