### ISSUE TITLE
Webview Safari UA without extension is detected in wrong version

### ISSUE THREAD

**Issue by christianhaller3000** [Financial-Times/polyfill-useragent-normaliser#175]
Hi @mhassan1 and @JakeChampion 
Thanks for the cool polyfill service.
We use it in an AWS Edge Lambda and are pretty happy.

with one exception: when requests are coming from our iOS app, too much polyfills are served

example:
`Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

this UA is detected as `ios_saf/11.0.0`

Do you have an idea how to solve this?

I made two failing tests, but no solution
https://github.com/Financial-Times/polyfill-useragent-normaliser/pull/174

**Comment by carles-thn** [comment]
@christianhaller3000 may be this fixes the issue? https://github.com/Financial-Times/useragent_parser/issues/100

Still, that doesn't seem to have landed in the production service. I made a question about that there: https://github.com/Financial-Times/polyfill-service/issues/2666

**Comment by christianhaller3000** [comment]
@carles-thn yes!

**Comment by christianhaller3000** [comment]
Sorry, but https://github.com/Financial-Times/useragent_parser/issues/100 is not fixing this issue :-(

**Comment by carles-thn** [comment]
@christianhaller3000 I'm not sure, the production CDN of the service works fine since It was updated by @JakeChampion to use polyfill-useragent-normaliser 1.10.1: https://github.com/Financial-Times/polyfill-service/pull/2669

**Comment by christianhaller3000** [comment]
![Bildschirmfoto 2022-03-04 um 14 50 25](https://user-images.githubusercontent.com/42344734/156775162-298ee303-181b-4a7b-9992-0e497f7fec9c.png)

can you have a look in this failing test?
https://github.com/Financial-Times/polyfill-useragent-normaliser/pull/174

**Comment by christianhaller3000** [comment]
Yay, it works!
I upgraded in [@polyfill-library](https://github.com/financial-times/polyfill-library) manually to @financial-times/polyfill-useragent-normaliser@2.0.1 to use it in the wild

Thank you :-)
