### ISSUE TITLE
QQ Browser is not recognised.

### ISSUE THREAD

**Issue by cravingsleep** [Financial-Times/polyfill-useragent-normaliser#27]
## Background
The QQ Browser is a browser developed by Tencent.

An example user agent from it is:
`Mozilla/5.0 (Linux; U; Android 9; zh-cn; vivo X21 Build/PKQ1.180819.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/9.9 Mobile Safari/537.36`

With the current detection this will show the family as `chrome 66`.

However, this browser does not support everything that Chrome supports (e.g. the `Intl` API) which leads to errors in polyfilling.

Do you think it's worth differentiating the QQ browser from Chrome?

**Comment by JakeChampion** [comment]
Hi @cravingsleep, thanks for the great issue :-)

If it is not the same as Chrome 66 then we should probably remove the aliasing/mapping that we are doing.

If we remove the aliasing/mapping then it would be detected as QQ Browser, which we don't support in our polyfill targeting. What that means is we would send QQ Browser all polyfills that have been requested and would put them all behind feature-detection.

I think it would be worth differentiating the QQ browser from Chrome, do you think we should?

**Comment by cravingsleep** [comment]
Hi @JakeChampion 

Yeah I agree with this approach.

I think it is better to have QQ different from Chrome. If that means having all polyfills behind feature detection then that's a worthwhile compromise. At least it will fix the `Intl` errors.

**Comment by JakeChampion** [comment]
This looks to be a bug in uap-core, which is what we are based upon. https://github.com/ua-parser/uap-core/pull/446
