### ISSUE TITLE
 Instagram ua 

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/polyfill-useragent-normaliser#3]
`Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 Instagram 8.4.0 (iPhone7,2; iPhone OS 9_3_2; nb_NO; nb-NO; scale=2.00; 750x1334`

Should return the ios_saf ua

**Comment by Jayphen** [comment]
https://github.com/Financial-Times/polyfill-useragent-normaliser/pull/4

I have an open PR for this

**Comment by Jayphen** [comment]
I don’t think this project is maintained.

**Comment by JakeChampion** [comment]
It is maintained

**Comment by Jayphen** [comment]
That’s good.

**Comment by Jayphen** [comment]
Sorry, I was just trying to help :)

**Comment by JakeChampion** [comment]
PR for this at #9

**Comment by JakeChampion** [comment]
Resolved via #9
