### ISSUE TITLE
Polyfill breaks websites on Pale Moon (XMLHTTPRequest?)

### ISSUE THREAD

**Issue by wolfbeast** [Financial-Times/polyfill-useragent-normaliser#7]
# Bug report

## What
- Misdetection of Pale Moon (and potentially other Firefox forks)
- XMLHTTPRequest polyfill wrong, resulting in:
  `TypeError: 'dispatchEvent' called on an object that does not implement interface EventTarget.`

## Details
I ran into this on PayPal of all places, breaking their web interface and preventing me from doing pretty much anything! This is a critical problem.
The console was spammed with the following types of errors:
```
18:55:39.359 TypeError: 'dispatchEvent' called on an object that does not implement interface EventTarget. 1 polyfill.js:6652:4
	XMLHttpRequest/nativeRequest.onreadystatechange https://cdn.polyfill.io/v3/polyfill.js:6652:4
	e.exports/n.onreadystatechange https://www.paypalobjects.com/web/res/*****/js/xhr-ads.min.js:1:17248
	e.exports/c.open https://www.paypalobjects.com/web/res/*****/js/xhr-ads.min.js:1:16760
	open https://cdn.polyfill.io/v3/polyfill.js:6692:3
	chatAsyncUtils/this.doGet https://www.paypal.com/smarthelp/js/minihelp/helpcenter-8ball-spark.js:410:7
	mountChat https://www.paypal.com/smarthelp/js/minihelp/helpcenter-8ball-spark.js:449:7
	helpcenter8ballSpark https://www.paypal.com/smarthelp/js/minihelp/helpcenter-8ball-spark.js:492:3
	<anonymous> https://www.paypal.com/smarthelp/js/minihelp/helpcenter-8ball-spark.js:23:11
```
And it would hang and block any action on their site.

A workaround was to feed polyfill.io an "official" Firefox useragent with a site-specific override:
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.9) Gecko/20100101 Firefox/60.9`

Our normal Firefox-compat UA string does NOT work and makes the lib bork:
`Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.9) Gecko/20100101 Goanna/4.1 Firefox/60.9 PaleMoon/28.4.0`
As an aside, we have 2 other UA modes our users may be using:
- Native: `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.9) Goanna/4.1 PaleMoon/28.4.0`
- Gecko compatibility: `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.9) Gecko/20100101 Goanna/4.1 PaleMoon/28.4.0`

## Additional information
Why are you not doing **feature detection** and are you relying on UA sniffing instead? Why are you overwriting functions like XHR which already exist?
Or for that matter: why are you polyfilling anything if you don't recognize a UA?

**Comment by wolfbeast** [comment]
Apologies if I posted this in the wrong repository.
It does indeed seem that the normalization has a bug in that case, or at the very least needs to be made aware of UXP applications.

**Comment by JakeChampion** [comment]
Hmm, for this one I would imagine we would have to depend on the gecko compat UA string and remove the Goanna and PaleMoon section with a regex, similar to #9.
