### ISSUE TITLE
Googlebot incorrectly identified as Chrome 41

### ISSUE THREAD

**Issue by AVGP** [Financial-Times/polyfill-useragent-normaliser#80]
Since May 2019, [Googlebot runs an evergreen Chrome](https://webmasters.googleblog.com/2019/05/the-new-evergreen-googlebot.html), but unfortunately this library normalises it to Chrome 41.

![Mobile-Friendly_Test_-_Google_Search_Console](https://user-images.githubusercontent.com/370246/84395191-3c4ddc80-abfe-11ea-8c5f-89591f390286.png)

This lead to a few websites using polyfill.io to experience rendering issues with Googlebot as lots of polyfills are loaded that aren't necessary anymore.

I made a demo page showing this at https://codepen.io/AVGP/full/BajKoqV that can be plugged into [the mobile-friendly test](https://codepen.io/AVGP/full/BajKoqV) for example to see how Googlebot sees the page.

**Comment by JakeChampion** [comment]
PR to fix this is https://github.com/Financial-Times/polyfill-useragent-normaliser/pull/81
