### ISSUE TITLE
Release 1.8.0?

### ISSUE THREAD

**Issue by AVGP** [Financial-Times/polyfill-useragent-normaliser#91]
Hey there - I'm curious when the [fix for Googlebot](https://github.com/Financial-Times/polyfill-useragent-normaliser/issues/80) is being released in the next version of the library and when this will approximately upstream to polyfill.io? We're seeing a few websites experiencing degraded rendering and wanted to check with y'all what the timeline looks like :)

**Comment by JakeChampion** [comment]
I've released a new version with all the updates in 1.9.0 👍

**Comment by AVGP** [comment]
Awesome, I'll ask on the polyfill-service repo when the hosted version of polyfill.io gets updated
